### ISSUE TITLE
Make signin and signup modal responsive to smaller screens.

### ISSUE THREAD

**Issue by sundarsv** [sundarsv/course6_upgrad_ass9nment#30]
Bloglist.html is expected to be responsive.  Signin and Signup header modals however do NOT respond to smaller breakpoints.  Handle this.

![image](https://user-images.githubusercontent.com/4122675/45585260-43e43280-b8ff-11e8-944b-a514fbaf937d.png)

**Comment by sundarsv** [comment]
Fixed via #31

**Comment by sugandhakhera** [comment]
fixed
