### ISSUE TITLE
resize of bloglist page beyond a limit shows only one blog.

### ISSUE THREAD

**Issue by sugandhakhera** [sundarsv/course6_upgrad_ass9nment#5]
![resize issue](https://user-images.githubusercontent.com/8520439/45302785-d9fc0f80-b531-11e8-8f99-6d4f59fca5d3.png)

**Comment by sundarsv** [comment]
@sugandhakhera - this looks like is working fine now.  Can we close this?

**Comment by sugandhakhera** [comment]
Happening to certain limit.

**Comment by sugandhakhera** [comment]
at all times, two blogs should be displayed acc to evaluation rubrics

**Comment by kanishka0706** [comment]
made this responsive till width 320px and responsive with all devices mentioned

**Comment by kanishka0706** [comment]
![screenshot 50](https://user-images.githubusercontent.com/38624598/45592191-81d76a00-b984-11e8-825f-b52b60860270.png)
![screenshot 51](https://user-images.githubusercontent.com/38624598/45592196-8bf96880-b984-11e8-988f-fdf68d0b5e84.png)

**Comment by sundarsv** [comment]
PR #33 to close this.
