### ISSUE TITLE
spacing issue while resizing - bloglist

### ISSUE THREAD

**Issue by sugandhakhera** [sundarsv/course6_upgrad_ass9nment#8]
![spacingissue](https://user-images.githubusercontent.com/8520439/45303229-f187c800-b532-11e8-85b3-954d98e03c9d.png)

---  While resizing, spacing between header, paragraph is very less.

**Comment by Apoorva2405** [comment]
Added fix in:
https://github.com/sundarsv/course6_upgrad_ass9nment/pull/9

**Comment by sundarsv** [comment]
closing based on approva's comment.
